# Basic Site Settings
locale                   : "en-US"
title                    : "Weihao Sun"
name                     : "Weihao Sun"
description              : "Ph.D. student in Management Science and Engineering"

url                      : "https://polarishealer.github.io"
baseurl                  : ""

repository               : "PolarisHealer/weihaosun.github.io"

# Author (Sidebar)
author:
  avatar           : "profile.png"
  name             : "Weihao Sun"
  bio              : "Ph.D. student, Hefei University of Technology"
  location         : "Hefei, Anhui, China"
  employer         : "Hefei University of Technology"
  email            : "weihaosun@mail.hfut.edu.cn"

  # Academic profile
  orcid            : "https://orcid.org/0009-0001-9831-9604"

  # GitHub
  github           : "PolarisHealer"
